<?php
$groupId = Mage::getSingleton('customer/session')->getCustomerGroupId();
$groupName = Mage::getModel('customer/group')->load($groupId)->getCode();
$isMultiply = Mage::helper("crconnect")->getGroupsIds($groupId);
?>
<div class="page-title">
    <h1><?php echo $this->__('Newsletter Subscription') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('form_before') ?>
<form action="<?php echo $this->getAction() ?>" method="post" id="form-validate">
    <fieldset>
<?php echo $this->getBlockHtml('formkey') ?>
        <ul class="form-list">
        <?php if ($this->isDefaultGroupUser()) { ?>            
                <?php if (!Mage::helper('crconnect')->isShowDefaultGroup() || !$isMultiply) { ?>
                    <li class="control"><input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?php echo $this->__('General Subscription') ?>"<?php if ($this->isDefaultSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="subscription"><?php echo $this->__('General Subscription') ?></label></li>
                <?php } ?>
                <?php if ($isMultiply) { ?>
                    <li class="control"><input type="checkbox" name="is_gsubscribed" id="gsubscription" value="1" title="<?php echo $groupName ?> Abonnement"<?php if ($this->isCustomSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="gsubscription"><?php echo Mage::helper('crconnect')->__('%s Subscription', $groupName) ?> </label></li>
                <?php } ?>
            <?php }else { ?>
                <li class="control"><input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?php echo $this->__('General Subscription') ?>"<?php if ($this->isDefaultSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="subscription"><?php echo $this->__('General Subscription') ?></label></li>
            <?php } ?>   
        </ul>
        <div class="buttons-set">
            <p class="back-link"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
            <button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
        </div>
    </fieldset>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
